#!/bin/sh
#
# pmver - determine the version of a perl module
#
# @(#) $Revision$
# @(#) $Id$
# @(#) $Source$
#
# Copyright (c) 2000 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo <was here> /\oo/\
#
# Share and enjoy!

# setup
#
PERL_ROOT="/usr/lib/perl5"

# parse args
#
if [ $# -lt 1 ]; then
    echo "usage: $0 MODULE::NAME" 1>&2
    exit 1
fi
file=`echo "$1" | sed -e 's#::#/#g'`

# firewall
#
if [ ! -d "$PERL_ROOT" ]; then
    echo "$0: cannot find $PERL_ROOT tree" 1>&2
    exit 2
fi

# look at the files
#
cd "$PERL_ROOT"
find . -path '*'"$file"'.pm' -print |
    while read file; do
	echo -n "$file: "
	perl -MExtUtils::MakeMaker -le 'print MM->parse_version(shift);' "$file"
    done
