#!/bin/bash
#
# pmver - determine the version of a perl module
#
# @(#) $Revision: 1.6 $
# @(#) $Id: pmver,v 1.6 2007/06/11 22:13:51 chongo Exp chongo $
# @(#) $Source: /usr/local/src/cmd/pmver/RCS/pmver,v $
#
# Copyright (c) 2000-2007 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo <was here> /\oo/\
#
# Share and enjoy!

# parse args
#
if [ $# -lt 1 ]; then
    echo "usage: $0 MODULE::NAME ..." 1>&2
    exit 1
fi
LANG=C

# determine perl locations
#
DIRSET=
for i in {/usr,/usr/local,/sw}/lib/perl{5,6} {/System,}/Library/Perl; do
    if [ -d "$i" ]; then
	DIRSET="$DIRSET $i"
    fi
done
if [ -z "$DIRSET" ]; then
    echo "cannot find any perl library directories" 1>&2
    exit 2
fi

# parse args
#
while [[ $# -gt 0 ]]; do
    file=`echo "$1" | sed -e 's#::#/#g'`

    # look at the files
    #
    find $DIRSET -ipath '*'"$file"'*.pm' -type f -print 2>/dev/null |
	sed -e 's/[	 ][	 ]*/\\ /g' |
	while read file; do
	    if [[ ! -r "$file" ]]; then
		echo "$0: cannot read $file" 1>&2
	    else
		echo -n "$file : "
		perl -MExtUtils::MakeMaker \
		  -le 'print MM->parse_version(shift);' "$file"
		status="$?"
		if [[ "$status" -ne 0 ]]; then
		    echo "$0: ExtUtils::MakeMaker exit $status on $file" 1>&2
		fi
	    fi
	done
    shift
done

# All done!!! -- Jessica Noll, Age 2
#
exit 0
